const router=require("express").Router(),{Op}=require("sequelize");
const {Job,Queue,Project,JobExecution}=require("../models"),auth=require("../middleware/auth"),{jobResponse,lowerEnum}=require("../utils");
async function queueAccess(id,userId){return Queue.findOne({where:{id},include:[{model:Project,where:{createdBy:userId,isActive:true},attributes:[]}]})}
async function jobAccess(id,userId){return Job.findOne({where:{id},include:[{model:Queue,include:[{model:Project,where:{createdBy:userId,isActive:true},attributes:[]}] }]})}
router.post("/jobs",auth,async(req,res,next)=>{try{const b=req.body||{},q=await queueAccess(b.queue_id,req.user.id);if(!q)return res.status(404).json({detail:"Queue not found"});if(q.isPaused)return res.status(409).json({detail:"Queue is paused"});if(b.idempotency_key){const e=await Job.findOne({where:{queueId:b.queue_id,idempotencyKey:b.idempotency_key}});if(e)return res.status(201).json(jobResponse(e));}const now=new Date(),sa=b.scheduled_at?new Date(b.scheduled_at):now;const j=await Job.create({queueId:q.id,jobType:b.job_type,payload:b.payload||{},status:sa<=now?"QUEUED":"SCHEDULED",priority:b.priority??0,maxAttempts:b.max_attempts??3,attemptCount:0,scheduledAt:sa,idempotencyKey:b.idempotency_key||null});res.status(201).json(jobResponse(j));}catch(e){next(e)}});
router.get("/jobs",auth,async(req,res,next)=>{try{const where={};if(req.query.queue_id)where.queueId=req.query.queue_id;if(req.query.status){const valid=["queued","scheduled","claimed","running","completed","failed"];if(!valid.includes(req.query.status))return res.status(400).json({detail:`Invalid job status. Valid values: ${valid.join(", ")}`});where.status=req.query.status.toUpperCase();}const rows=await Job.findAll({where,include:[{model:Queue,include:[{model:Project,where:{createdBy:req.user.id,isActive:true},attributes:[] }],attributes:[]}],order:[["priority","DESC"],["createdAt","DESC"]],limit:Math.min(Number(req.query.page_size||20),100),offset:(Math.max(Number(req.query.page||1),1)-1)*Math.min(Number(req.query.page_size||20),100)});const total=await Job.count({where,include:[{model:Queue,required:true,include:[{model:Project,where:{createdBy:req.user.id,isActive:true},attributes:[]}]}]});res.json({items:rows.map(jobResponse),total,page:Math.max(Number(req.query.page||1),1),page_size:Math.min(Number(req.query.page_size||20),100)});}catch(e){next(e)}});
router.get("/jobs/:id",auth,async(req,res,next)=>{try{const j=await jobAccess(req.params.id,req.user.id);if(!j)return res.status(404).json({detail:"Job not found"});const ex=await JobExecution.findAll({where:{jobId:j.id},order:[["attemptNumber","ASC"]]});res.json({...jobResponse(j),executions:ex.map(e=>({id:e.id,job_id:e.jobId,worker_id:e.workerId,attempt_number:e.attemptNumber,status:lowerEnum(e.status),started_at:e.startedAt,finished_at:e.finishedAt,duration_ms:e.durationMs,error_message:e.errorMessage,result:e.result,created_at:e.createdAt}))});}catch(e){next(e)}});
router.post("/jobs/:id/retry",auth,async(req,res,next)=>{try{const j=await jobAccess(req.params.id,req.user.id);if(!j)return res.status(404).json({detail:"Job not found"});if(j.status!=="FAILED")return res.status(409).json({detail:"Only failed jobs can be manually retried"});const q=await Queue.findByPk(j.queueId);if(!q)return res.status(404).json({detail:"Queue not found"});if(q.isPaused)return res.status(409).json({detail:"Queue is paused"});j.status="QUEUED";j.failedAt=null;j.lastError=null;j.scheduledAt=new Date();await j.save();res.json(jobResponse(j));}catch(e){next(e)}});
module.exports=router;
